Add ability to set recommended maps and mods
FAForever/faf-moderator-client pull request #124
Opened 2021-05-24 22:42 UTC by Sheikah45

tied to https://github.com/FAForever/faf-java-api/pull/472

2021-05-24 22:42 UTC, Sheikah45 commented
@Brutus5000 don't have access to request reviews on this one

2021-06-03 11:20 UTC, Brutus5000 requested changes
Please stop converting everything into * imports

2021-06-03 11:20 UTC, Brutus5000 commented on src/main/java/com/faforever/moderatorclient/ui/ViewHelper.java
> +        extractors.put(recommendColumn, ModFX::isRecommended);
I don't think we want to offer copying boolean values via context menu. Please remove the extractors.put

2021-06-03 11:20 UTC, Brutus5000 commented on src/main/java/com/faforever/moderatorclient/ui/ViewHelper.java
> +        extractors.put(recommendColumn, MapFX::isRecommended);
I don't think we want to offer copying boolean values via context menu. Please remove the extractors.put

2021-06-03 11:41 UTC, Sheikah45 commented
Sigh the intellij auto optimization is changing to * guess I will have to turn that off

2021-06-03 12:17 UTC, Brutus5000 approved these changes

2021-06-03 12:17 UTC, merged