Feature/setting veto system fields
FAForever/faf-moderator-client pull request #229
Opened 2024-10-12 18:37 UTC by K-ETFreeman

fixes #227
requires updated database and api with veto system fields updates

maxTokenPerMap: set "D" into the field as "Dynamic". I think this is more clear than 0. 
![image](https://github.com/user-attachments/assets/01a4ba1d-a497-41cc-b613-3bb65fd59c58)
Under the hood, D transforms to 0 anyway. Would be nice to have null instead of 0, but not possible currently due to patch request limitations in current api-service code.

2024-11-29 16:45 UTC, Sheikah45 requested changes

2024-11-29 16:45 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
Use a TextFormatter instead of parsing and limiting the values and throwing an exception ourselves.

2024-11-29 16:45 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
TextFormatter

2024-11-29 16:45 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
TextFormatter

2024-11-29 17:05 UTC, K-ETFreeman commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
like that?
`        vetoTokensPerPlayerInput.setTextFormatter(new TextFormatter<>(new IntegerStringConverter(), 0, change -> {
            String newText = change.getControlNewText();
            try {
                int value = Integer.parseInt(newText);
                if (value < 0 || value > 255) {
                    return null;
                }
                return change; // Accept change
            } catch (NumberFormatException e) {
                log.error(e.getMessage());
                return null; // Reject change
            }
        }));

        vetoTokensPerPlayerInput.textProperty().addListener((observable, oldValue, newValue) -> {
            try {
                int value = Integer.parseInt(newValue);
                if (!Objects.equals(property.get(), value)) {
                    property.set(value);
                }
            } catch (NumberFormatException e) {
                log.error(e.getMessage());
            }
        });`

2024-11-29 18:01 UTC, K-ETFreeman commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
tbh its just make everything worse because i need manually allow changing caret position and deletion etc

2024-11-29 18:14 UTC, K-ETFreeman commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        });
or should i put property.set inside the formatter too

2024-12-01 19:56 UTC, Sheikah45 requested changes

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +    public HBox maxTokensPerMapHBox;
I would follow convention and make these not public and use @FXML

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +                log.debug(String.valueOf(bracket.maxTokensPerMapProperty().get()));
This log statement isn't needed anymore

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +                bracket.maxTokensPerMapProperty().set(1);
```suggestion
                bracket.setMaxTokensPerMap(0);
            } else {
                bracket.setMaxTokensPerMap(1);
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        dynamicMaxTokensPerMapCheckBox.setSelected(bracket.maxTokensPerMapProperty().get() == 0);
```suggestion
        dynamicMaxTokensPerMapCheckBox.setSelected(bracket.getMaxTokensPerMap() == 0);
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        maxTokensPerMapSpinner.getValueFactory().setValue(bracket.maxTokensPerMapProperty().get());
```suggestion
        maxTokensPerMapSpinner.getValueFactory().setValue(bracket.getMaxTokensPerMap());
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        maxTokensPerMapSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.maxTokensPerMapProperty().set(newValue));
```suggestion
        maxTokensPerMapSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.setMaxTokensPerMap(newValue));
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        vetoTokensPerPlayerSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.vetoTokensPerPlayerProperty().set(newValue));
```suggestion
        vetoTokensPerPlayerSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.setVetoTokensPerPlayer(newValue));
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        minimumMapsAfterVetoSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.minimumMapsAfterVetoProperty().set(newValue));
```suggestion
        minimumMapsAfterVetoSpinner.valueProperty().addListener((observable, oldValue, newValue) -> bracket.setMinimumMapsAfterVeto(newValue));
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        minimumMapsAfterVetoSpinner.getValueFactory().setValue(bracket.minimumMapsAfterVetoProperty().get());
```suggestion
        minimumMapsAfterVetoSpinner.getValueFactory().setValue(bracket.getMinimumMapsAfterVeto());
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/BracketListViewController.java
> +        vetoTokensPerPlayerSpinner.getValueFactory().setValue(bracket.vetoTokensPerPlayerProperty().get());
```suggestion
        vetoTokensPerPlayerSpinner.getValueFactory().setValue(bracket.getVetoTokensPerPlayer());
```

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/LadderMapPoolController.java
> +                apiService.patch(navigator, dto);
This should be a method inside mapService

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/LadderMapPoolController.java
> +                apiService.patch(navigator, dto);
like the changes to mappoolassignments below

2024-12-01 19:56 UTC, Sheikah45 commented on src/main/java/com/faforever/moderatorclient/ui/main_window/LadderMapPoolController.java
> +    private final FafApiCommunicationService apiService;
This should only need mapService

2024-12-25 12:54 UTC, Sheikah45 approved these changes

2025-10-09 18:13 UTC, merged